version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: webpack-cli
    versions:
    - 4.3.1
    - 4.4.0
  - dependency-name: ts-loader
    versions:
    - 8.0.13
    - 8.0.14
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@types/yargs"
    versions:
    - 15.0.12
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.7
